// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh-fQV-q1-l7wuZyMgGSrpE1pPWW7AVM4',
    appId: '1:359347316467:web:3ea249755496340de43986',
    messagingSenderId: '359347316467',
    projectId: 'repayer-stg',
    authDomain: 'repayer-stg.firebaseapp.com',
    storageBucket: 'repayer-stg.appspot.com',
    measurementId: 'G-K2WDSNHN2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-eUqysVcYUWocwR9BAi0ie6cZxTWL6ng',
    appId: '1:359347316467:android:6e91a4d6e298f87ce43986',
    messagingSenderId: '359347316467',
    projectId: 'repayer-stg',
    storageBucket: 'repayer-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZcgSr9Lz6GCMx1q6Q2nptMPvo865m2gU',
    appId: '1:359347316467:ios:69b5723dead8a773e43986',
    messagingSenderId: '359347316467',
    projectId: 'repayer-stg',
    storageBucket: 'repayer-stg.appspot.com',
    iosClientId: '359347316467-ibls2091psba003dvtdpbt3crrb3ej9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.repayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZcgSr9Lz6GCMx1q6Q2nptMPvo865m2gU',
    appId: '1:359347316467:ios:69b5723dead8a773e43986',
    messagingSenderId: '359347316467',
    projectId: 'repayer-stg',
    storageBucket: 'repayer-stg.appspot.com',
    iosClientId: '359347316467-ibls2091psba003dvtdpbt3crrb3ej9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.repayer',
  );
}
